<?php

/*
 * This file is part of the TecnocreacionesVzlaEntityBundle package.
 * 
 * (c) www.tecnocreaciones.com.ve
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tecnocreaciones\Vzla\EntityBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * 
     * @param \Tecnocreaciones\Vzla\EntityBundle\Entity\State $state
     * @return type
     */
    function getQueryByState($state) {
        $qb = $this->createQueryBuilder('c');
        if($state === null){
           $qb->setMaxResults(0);
           return $qb;
        }
        $qb
                ->andWhere('c.state = :state')
                ->setParameter('state', $state)
                ;
        return $state;
    }
    /**
     * Retorna las ciudades por el municipio
     */
    function findCitiesByMunicipality($municipalityId) {
        $qb = $this->createQueryBuilder('c');
        $qb
                ->innerJoin('c.municipality', 'm')
                ->andWhere('c.active = 1')
                ->andWhere('m.id = :municipality')
                ->setParameter('municipality', $municipalityId)
                ;
        return $qb->getQuery()->getResult();
    }
    /**
     * Retorna las ciudades por la parroquia
     */
    function findCitiesByParish($parishId) {
        $qb = $this->getQueryAllActive();
        $qb
                ->innerJoin('c.parishes', 'c_p')
                ->andWhere('c_p.id = :parish')
                ->setParameter('parish', $parishId)
                ;
            $this->addSort($qb);
        return $qb->getQuery()->getResult();
    }
    
    protected function getAlias() {
        return "c";
    }
}
