<?php

/*
 * This file is part of the TecnocreacionesVzlaEntityBundle package.
 * 
 * (c) www.tecnocreaciones.com.ve
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tecnocreaciones\Vzla\EntityBundle\Repository;

/**
 * MunicipalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipalityRepository extends EntityRepository
{
    function findMunicipalitiesByState($state)
    {
        $qb = $this->createQueryBuilder('m');
        $qb
                ->innerJoin('m.state', 's')
                ->andWhere('m.active = 1')
                ->andWhere('s.id = :state')
                ->setParameter('state', $state)
                ;
        return $this->findQueryMunicipalitiesByState($state)->getQuery()->getResult();
    }
    
    function findQueryMunicipalitiesByState($state)
    {
        $qb = $this->createQueryBuilder('m');
        $qb
                ->innerJoin('m.state', 's')
                ->andWhere('m.active = 1')
                ->andWhere('s.id = :state')
                ->setParameter('state', $state)
                ;
        return $qb;
    }
}
