<?php

/*
 * This file is part of the TecnocreacionesVzlaEntityBundle package.
 * 
 * (c) www.tecnocreaciones.com.ve
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tecnocreaciones\Vzla\EntityBundle\Repository;

/**
 * Repositorio de parroquia
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParishRepository extends EntityRepository
{
    public function findByMunicipality($municipality) 
    {
        $qb = $this->getQueryAllActive();
        $qb
            ->innerJoin("p.municipality","p_m")
            ->andWhere("p_m.id = :municipality")
            ->setParameter("municipality", $municipality)
            ;
            $this->addSort($qb);
        return $qb->getQuery()->getResult();
    }
    
    protected function getAlias() {
        return "p";
    }
}
