Tecnocreaciones\Vzla\EntityBundle\Entity\City:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list]
        description:
            expose: true
            groups: [list]
        capital:
            expose: true
            groups: [list]
        active:
            expose: true
            groups: [list]
        state:
            expose: true
            groups: [api_state]