Tecnocreaciones\Vzla\EntityBundle\Entity\Municipality:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list,show,state]
        description:
            expose: true
            groups: [list,show,state]
        state:
            expose: true
            groups: [state]
        active:
            expose: true
            groups: [list,show,state]
        parishes:
            expose: true
            groups: [parishes]