Tecnocreaciones\Vzla\EntityBundle\Entity\Parish:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list,show,country]
        description:
            expose: true
            groups: [list,show,country]